### ISSUE TITLE
Commits to development branch should deploy to staging

### ISSUE THREAD

**Issue by saoirse-zee** [saoirse-zee/bookit-mobile#61]
It's not clear where commits to development are deployed. The concourse logs read `https://exp.host/@buildit/bookit-mobile`, which is the production slug, but the changes do not seem to show up in the prod app.

Reference Concourse logs: https://concourse.buildit.tools/teams/bookit-mobile/pipelines/development/jobs/Publish%20to%20Staging/builds/4#L5a381573:327

**Comment by saoirse-zee** [comment]
Should this "release channel" stuff be in there?

https://github.com/saoirse-zee/bookit-mobile/blob/development/concourse/development-pipeline.yml#L169

**Comment by BenAychh** [comment]
That should not be there... gonna try to pull that and republish, will check in with you.

**Comment by BenAychh** [comment]
I think this is fixed, might have been an expo issue.
